sudo: false

language: cpp

install:
  # Set the anaconda environment
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/bin/activate
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels defaults
  - conda update -q --all
  - conda install conda-build anaconda-client
  # build
  - conda build -c $MY_CONDA_CHANNEL conda-recipe

script:
  - echo "No test scripts to be run!"

deploy:
  provider: script
  script: find $HOME/miniconda/conda-bld/noarch -name "*.tar.bz2" -exec anaconda -t $CONDA_TOKEN upload {} \;
  on:
    tags: true
