package:
    name: bsread
    version: 0.0.4
source:
    git_tag: 0.0.4
    git_url: https://github.psi.ch/scm/st/bsread_python.git

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - zmq

build:
  entry_points:
    - bs = bsread.bs:main

about:
    home: https://github.psi.ch/projects/ST/repos/bsread_python/browse
    summary: "BSREAD Python library."
