package:
    name: bsread
    version: 0.0.14
source:
    git_tag: 0.0.14
    git_url: https://github.psi.ch/scm/st/bsread_python.git

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pyzmq

build:
  entry_points:
    - bs = bsread.bs:main
    - bs-source = bsread.bs_source:main

about:
    home: git@git.psi.ch:sf_daq/bsread_python.git
    summary: "BSREAD Python library."
