package:
    name: bsread
    version: 0.0.1
source:
    git_tag: 0.0.1
    git_url: https://github.psi.ch/scm/st/bsread_python.git

requirements:
    build:
        - python
        - setuptools
    run:
        - python

build:
  entry_points:
    - bstat = bsread.bsread_util:main
    # - pylauncher-convert = pylauncher.convert.convert:main

about:
    home: https://github.psi.ch/projects/ST/repos/bsread_python/browse
    summary: "BSREAD Python library."
