package:
    name: bsread
    version: 0.0.16
#source:
#    git_tag: 0.0.14
#    git_url: git@git.psi.ch:sf_daq/bsread_python.git
source:
    path: ../..

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pyzmq

build:
  entry_points:
    - bs = bsread.bs:main
    - bs-source = bsread.bs_source:main

about:
    home: git@git.psi.ch:sf_daq/bsread_python.git
    summary: "BSREAD Python library."
