package:
    name: bsread
    version: 0.8.10
#source:
#    git_tag: 0.0.14
#    git_url: git@git.psi.ch:sf_daq/bsread_python.git
source:
    path: ..

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - mflow
        - bitshuffle
        - numpy
        - pyzmq
        - requests

build:
  entry_points:
    - bs = bsread.bs:main

about:
    home: git@git.psi.ch:sf_daq/bsread_python.git
    summary: "BSREAD Python library."
