package:
    name: bsread
    version: 1.4.2
#source:
#    git_tag: 0.0.14
#    git_url: git@git.psi.ch:sf_daq/bsread_python.git
source:
    path: ..

build:
    noarch: python
    number: 2
    script: python -m pip install --no-deps --ignore-installed .
    entry_points:
        - bs = bsread.bs:main

requirements:
    build:
        - python
        - setuptools
        - pip
    run:
        - python
        - mflow >=0.0.23
        - bitshuffle
        - numpy
        - pyzmq
        - requests

about:
    home: git@git.psi.ch:sf_daq/bsread_python.git
    summary: "BSREAD Python library."
